<?php session_start(); ?>
<html>
<head>
  <title>Add Team</title>
  <link rel="stylesheet" href="styles/add.css">
  <!--favicon generated by http://realfavicongenerator.net/-->
  <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicons/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicons/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicons/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/favicons/manifest.json">
  <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
  <link rel="shortcut icon" href="/favicons/favicon.ico">
  <meta name="apple-mobile-web-app-title" content="Scouting">
  <meta name="application-name" content="Scouting">
  <meta name="msapplication-config" content="/favicons/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">
</head>
<?php
  #check if logged in and redirect if not
  if (!isset($_SESSION["loggedIn"])) {
  	header( 'Location: '.getRootDir().'login.php?redirect=addTeam.php');
  	exit();
  }
  if($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST["team"])) {
    require 'functions.php';
    $result = formatAndQuery('SELECT number FROM %s WHERE number = %sv', $TeamDataTable, $_POST["team"]);
  	if($result->num_rows == 0) {
      formatAndQuery('INSERT INTO %s VALUES (%sv,"","")', $TeamDataTable, $_POST["team"]);
      header('Location: edit.php?team='.clean($_POST["team"]));
      exit();
    }
  }
 ?>

<body>
  <div id="main">
    <h1>Add Team</h1>
    <form action="<?php echo(htmlentities($_SERVER['PHP_SELF'])); ?>" method="post" id="mainf">
      <input type="text" id="teaminput" name="team">
      <input type="submit" id="submitbutton">
      <p id="exists" style="display: none;">Team alredy exists in database</p>
    </form>
  </div>
</body>
<script src="scripts/jquery-3.1.1.min.js"></script>
<script>
var request;
function validateTeam(team, callback) {
  request = new XMLHttpRequest();
  request.onreadystatechange = function() {
    if(this.readyState == 4 && this.status == 200) {
      callback(this.responseText == "TRUE");
    }
  }
  request.open("GET", "checkTeam.php?team="+encodeURIComponent(team), true);
  request.send();

}
function toggleTeam(allow) {
  var button = $("#submitbutton");
  var exists = $("#exists");
  if(allow) {
    button.prop("disabled",false);
    exists.hide();
  } else {
    button.prop("disabled", true);
    exists.show();
  }
}
$(document).ready(function() {
  $("#teaminput").on('keypress', function(e) {
  	var chr = String.fromCharCode(e.which);
  	if ("1234567890".indexOf(chr) < 0 && e.which != 8) {
  		return false;
  	}
  })
  $("#teaminput").on('input', function(e) {
    validateTeam($(e.target).val(), toggleTeam);
  })
});
</script>
</html>
