<?php session_start(); ?>
<?php require 'functions.php'; ?>
<html>
	<head>
		<title>Scouting website</title>
		<link rel="stylesheet" href="styles/style.css">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="no" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

		<!--favicon generated by http://realfavicongenerator.net/-->
		<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
		<link rel="icon" type="image/png" href="/favicons/favicon-32x32.png" sizes="32x32">
		<link rel="icon" type="image/png" href="/favicons/android-chrome-192x192.png" sizes="192x192">
		<link rel="icon" type="image/png" href="/favicons/favicon-16x16.png" sizes="16x16">
		<link rel="manifest" href="/favicons/manifest.json">
		<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
		<link rel="shortcut icon" href="/favicons/favicon.ico">
		<meta name="apple-mobile-web-app-title" content="Scouting">
		<meta name="application-name" content="Scouting">
		<meta name="msapplication-config" content="/favicons/browserconfig.xml">
		<meta name="theme-color" content="#ffffff">
	</head>
<body>

	<?php
	function getFilterFromData($key, $data, $place) {
		$types = array("string","select","boolean","number");
		if(!in_array($data["type"],$types)) {
			return False;
		}
		$out = '<div class="filtercontainer" data-place="'.$place.'" data-key="'.$key.'" data-type="'.clean($data["type"]).'">';
		$out .= '<input type="checkbox" class="filterbox">';
		$out .= '<p class="filterlabel">'.$data["display_name"]."</p>";
		switch($data["type"]) {
			case "string":
				$out .= '<input type="text">';
				break;
			case "select":
				$out .= '<select>';
				foreach($data["values"] as $option) {
					$out .= "<option>".clean($option)."</option>";
				}
				$out .="</select>";
				break;
			case "boolean":
				$out .= '<select><option>Yes</option><option>No</option></select>';
				break;
			case "number":
				$out .= '<input type="number">';
				break;
		}
		$out .= '</div>';
		return $out;
	}
	 ?>

	<h1 id="title">Scouting <img id="hamburger" src="images/hamburger.png" height="50" /></h1>

	<div hidden id="hamburgermenu">
		<ul id="menuitems">
			<li id="searchli">Search</li>
			<li id="filterli">Filters</li>
			<a href="addTeam.php"><li id="addli">Add Team</li></a>
			<?php
			if(isset($_SESSION["loggedIn"]) and $_SESSION["loggedIn"] and checkIsAdmin($_SESSION["user"], $_SESSION["pass"])) {
				echo('<a href="editusers.php"><li id="usersli">Manage Users</li></a>');
				echo('<a href="editschema.php"><li id="schemali">Edit Schema</li></a>');
			}
			 ?>
		</ul>
	</div>

	<div hidden id="TeamSearch">
		<input name="TeamSearchbox" placeholder="Search for a team here!" pattern="[0-9]*" type="number">
		<div id="closesearchbar"> X </div>
	</div>

	<div hidden id="Filters">
		<?php
		if(file_exists("schema.json")) {
			$json = json_decode(file_get_contents("schema.json"), True);
			$year = getYearData($json, getDefaultYear())[1];
			if($year === false) {
				echo("<p>Schema for this year does not exist</p>");
				exit();
			}
		} else {
			echo("<p>schema.json does not exist!</p>");
			exit();
		}
		 ?>
		 <p id="robotfilterlabel">Robot filters:</p>
		 <?php
		 	foreach($year["robotdata"] as $key=>$value) {
				$data = getFilterFromData($key,$value,"robot");
				if($data !== False) {
					echo($data);
				}
			}
		  ?>
			<p id="matchfilterlabel">Match filters:</p>
			<?php
			foreach($year["matchdata"] as $key=>$value) {
				$data = getFilterFromData($key,$value,"match");
				if($data !== False) {
					echo($data);
				}
			}
			 ?>
	</div>

	<div id="container">
	</div>
	<?php
	if(isset($_SESSION["loggedIn"])) {
		echo('<div id="loginbox"><p style="margin:2px;"><a id="logoutLink" href="logout.php">Log Out: '.$_SESSION["user"].'</a></p></div>');
	}
	?>

	<script src="scripts/jquery-3.1.1.min.js"></script>
	<script src="scripts/filters.js"></script>
	<script src="scripts/updateList.js"></script>
	<script src="scripts/hamburger.js"></script>
	<script src="scripts/search.js"></script>
</body>
</html>
