<?php session_start(); ?>
<html>
	<head>
		<title>Log in</title>
		<link rel="stylesheet" href="styles/style.css">
		<?php
		require 'functions.php';

		$passFailed = False;

		if ($_SERVER["REQUEST_METHOD"] == "GET" and isset($_GET["redirect"])) {
			$redirect = $_GET['redirect'];
		}
		if ($_SERVER["REQUEST_METHOD"] == "POST") {
			if(isset($_POST["redirect"])) {
				$redirect = $_POST["redirect"];
			}
			$user = clean($_POST["user"]);
			$pass = clean($_POST["pass"]);
			$year = clean($_POST["year"]);
			if (checkUserPassword($user, $pass)) {
				$_SESSION["user"] = $user;
				$_SESSION["pass"] = $pass;
				$_SESSION["year"] = $year;
				$_SESSION["loggedIn"] = True;
				setCSRFToken();
			} else {
				$passFailed = True;
			}
		}
		if (isset($_SESSION["loggedIn"]) and $_SESSION["loggedIn"]) {
			if (isset($_POST["redirect"])) {
				header( 'Location: '.getRootDir().clean($_POST["redirect"]));
				exit();
			}
			if (isset($_GET["redirect"])) {
				header( 'Location: '.getRootDir().clean($_GET["redirect"]));
				exit();
			}
			header( 'Location: '.getRootDir().'index.php');
			exit();
		}
		?>

		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="no" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

		<!--favicon generated by http://realfavicongenerator.net/-->
		<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
		<link rel="icon" type="image/png" href="/favicons/favicon-32x32.png" sizes="32x32">
		<link rel="icon" type="image/png" href="/favicons/android-chrome-192x192.png" sizes="192x192">
		<link rel="icon" type="image/png" href="/favicons/favicon-16x16.png" sizes="16x16">
		<link rel="manifest" href="/favicons/manifest.json">
		<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
		<link rel="shortcut icon" href="/favicons/favicon.ico">
		<meta name="apple-mobile-web-app-title" content="Scouting">
		<meta name="application-name" content="Scouting">
		<meta name="msapplication-config" content="/favicons/browserconfig.xml">
		<meta name="theme-color" content="#ffffff">
	</head>
	<body>
		<form id="loginform" action="<?php echo(clean($_SERVER["PHP_SELF"]));?>" method="post">
			<p id="userlabel">Username:</p><br>
			<input id="usernamefield" type="text" name="user" <?php if($_SERVER["REQUEST_METHOD"] == "POST"){echo('value="'.$user.'"');}?>><br>
			<p id="passlabel">Password:</p><br>
			<input id="passwordfield" type="password" name="pass"><br>
			<?php
			if(file_exists("schema.json")) {
				$json = json_decode(file_get_contents("schema.json"), True);
				echo('<select id="yearselectfield" name="year">');
				$years = array();
				foreach($json as $year) {
					$years[] = $year["year"];
	      }
				rsort($years);
				foreach($years as $year) {
					if($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST["year"]) && $_POST["year"] == $year){
						echo('<option value='.$year.' selected="selected">'.$year.'</option>');
					} else {
						echo('<option value='.$year.'>'.$year.'</option>');
					}
				}
				echo('</select>');
			}

			if ($passFailed) {
				echo('<p style="font-size: 25px; color: red;">Access Denied: Check Username and Password</p>');
			}
			if(isset($redirect)){
				echo('<input type="hidden" name="redirect" value="'.clean($redirect).'">');
			}
			?>
			<input type="submit" hidden value="Login"><!-- Push enter to login -->
			<div id="submitbtn" onclick="javascript:parentNode.submit();">login</div>
		</form>
	</body>
</html>
