<?php session_start(); ?>
<html>
	<head>
		<title>Log in</title>
		<link rel="stylesheet" href="style.css">
		<?php
		if ($_SERVER["REQUEST_METHOD"] == "GET") {
			$redirect = $_GET['redirect'];
		}
		function clean($data) {
		  $data = trim($data);
		  $data = stripslashes($data);
		  $data = htmlspecialchars($data);
		  return $data;
		}
		if ($_SERVER["REQUEST_METHOD"] == "POST") {
			$user = clean($_POST["user"]);
			$pass = clean($_POST["pass"]);
			if(isset($_POST["redirect"])) {
				$redirect = $_POST["redirect"];
			}
			$DB = new mysqli("localhost",$user,$pass,"frcteam4999");
			$_SESSION["user"] = $user;
			$_SESSION["pass"] = $pass;
			if (!$DB->connect_error) {
				$_SESSION["loggedIn"] = True;
			}
		}
		if (isset($_SESSION["loggedIn"])) {
			if (isset($_POST["redirect"])) {
				header( 'Location: https://frcteam4999.jordanpowers.net/'.clean($_POST["redirect"]));
				exit();
			}
			header( 'Location: https://frcteam4999.jordanpowers.net/index.php');
			exit();
		}
		?>
	
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="no" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		
		<!--favicon generated by http://realfavicongenerator.net/-->
		<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
		<link rel="icon" type="image/png" href="/favicons/favicon-32x32.png" sizes="32x32">
		<link rel="icon" type="image/png" href="/favicons/android-chrome-192x192.png" sizes="192x192">
		<link rel="icon" type="image/png" href="/favicons/favicon-16x16.png" sizes="16x16">
		<link rel="manifest" href="/favicons/manifest.json">
		<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
		<link rel="shortcut icon" href="/favicons/favicon.ico">
		<meta name="apple-mobile-web-app-title" content="Scouting">
		<meta name="application-name" content="Scouting">
		<meta name="msapplication-config" content="/favicons/browserconfig.xml">
		<meta name="theme-color" content="#ffffff">
	</head>
	<body>
		<form id="loginform" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="post">
			<p id="userlabel">Username:</p><br>
			<input id="usernamefield" type="text" name="user" <?php if($_SERVER["REQUEST_METHOD"] == "POST"){echo('value="'.$user.'"');}?>><br>
			<p id="passlabel">Password:</p><br>
			<input id="passwordfield" type="password" name="pass"><br>
			<?php
			if ($DB->connect_error) {
				$error = $DB->connect_error;
				if(is_int(strpos($error, "Access denied"))) {
					echo('<p style="font-size: 25px; color: red;">Access Denied: Check Username and Password</p>');
				} else {
					echo('<p sytle = "font-size: 15px; font-color: red;">'.$error.'</p>');
				}
			}
			if(isset($redirect)){
				echo('<input type="hidden" name="redirect" value="'.$redirect.'">');
			}
			?>
			<input type="submit" hidden value="Login"><!-- Push enter to login -->
			<div id="submitbtn" onclick="javascript:parentNode.submit();">login</div>
		</form>
	</body>
</html>
